server {
    # Listen on port 8080 to match Cloud Run requirements
    listen 8080;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;

        # Enable Basic Authentication
        auth_basic "Restricted Access - MLP & Solar App";
        auth_basic_user_file /etc/nginx/.htpasswd;
    }
}
